spring:
  application:
    name: microservice-kafka.notification-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: jackson14042004@gmail.com
    password: fybnhqmmhlwwzgvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000

app:
  kafka:
    consumer-group-id: notification-group
  topics:
    order-created: order-created-topic
    order-processed: order-processed-topic

server:
  port: 8083

