spring:
  application:
    name: microservice-kafka.notification-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: jackson14042004@gmail.com
    password: fybnhqmmhlwwzgvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
server:
  port: 8083

app:
  topics:
    order-created: order-created-topic
    order-processed: order-processed-topic
    inventory-check: inventory-check-topic
    inventory-updated: inventory-updated-topic
  kafka:
    consumer-groups:
      order-created: order-created-group
      order-processed: order-processed-group
      inventory-check: inventory-check-group
      inventory-updated: inventory-update-group
      notification-order-created: notification-order-created-group
      notification-order-processed: notification-order-processed-group
      notification-inventory-check: notification-inventory-check-group

